spring.application.name=yogobi
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:yogobi}
spring.datasource.username=${POSTGRES_USER:yogobi}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.sql.init.mode=never
