-- 카탈로그 결손 기록 (D-17 · G-12). CSV에 없어서 요청된 것을 남긴다 — requested_cnt 가 팀의 CSV 수집 우선순위다.
-- V9 의 catalog_report("있는데 값이 틀렸다")와 다른 것을 센다: 여기는 "아예 없다".
-- 계산에는 쓰지 않는다. 카탈로그(mobile_plan·subscription_tier) 진입은 사람이 CSV에 반영할 때만이다.
-- 수집·검증 컬럼(금액·출처 2곳·수집일)은 수집기가 생기는 P2에서 추가한다.
CREATE TABLE catalog_candidate (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          TEXT NOT NULL CHECK (kind IN ('MOBILE_PLAN', 'SUBSCRIPTION_TIER')),
    query_text    TEXT NOT NULL CHECK (btrim(query_text) <> '' AND length(query_text) <= 200),
    status        TEXT NOT NULL CHECK (status IN ('REQUESTED', 'PENDING', 'VERIFIED', 'REJECTED')),
    requested_cnt INT NOT NULL DEFAULT 1 CHECK (requested_cnt > 0),
    last_requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (kind, query_text)
);
