-- 카탈로그 원본(합본 CSV) 변경 감사 기록. D-24 리스크 ①("누가 언제 무엇을 바꿨는지 없다") 해소.
-- 원본이 파일이라 git 이력이 남지 않는다 — 이 표가 유일한 변경 이력이다.
-- 실패한 시도(DB 반영 실패로 되돌린 변경)도 남긴다. 시도 자체가 감사 대상이다.
-- 회원 FK 를 걸지 않는다: 운영자가 탈퇴해도 "누가 바꿨는지"는 남아야 한다(D-11 과 같은 이유).
CREATE TABLE catalog_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT NOT NULL,          -- 변경한 운영자 app_user.id (FK 아님 — 탈퇴해도 보존)
    action      TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    dataset     TEXT NOT NULL CHECK (btrim(dataset) <> '' AND length(dataset) <= 64),
    row_key     TEXT NOT NULL CHECK (length(row_key) <= 500),
    before_row  TEXT CHECK (length(before_row) <= 4000),   -- 변경 전 CSV 행. CREATE 는 NULL
    after_row   TEXT CHECK (length(after_row) <= 4000),    -- 변경 후 CSV 행. DELETE 는 NULL
    outcome     TEXT NOT NULL CHECK (outcome IN ('APPLIED', 'FAILED')),
    detail      TEXT CHECK (length(detail) <= 1000),       -- FAILED 사유(예외 종류). APPLIED 는 NULL
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_catalog_audit_created ON catalog_audit(created_at DESC);
CREATE INDEX idx_catalog_audit_actor ON catalog_audit(actor_id, created_at DESC);
