-- 카탈로그 원본 변경 제안·승인(D-28). D-24 리스크 ①의 나머지("사전 승인 단계 없음")를 없앤다.
-- 쓰기는 즉시 반영되지 않고 여기 PENDING 으로 쌓인다. 승인해야 파일·DB 에 반영된다.
-- payload 는 요청 본문(JSON 문자열). DELETE 는 본문이 없으므로 NULL.
-- 제안자·승인자를 따로 남긴다 — 자기 승인을 허용하더라도 "누가 제안하고 누가 승인했는지"는 구분돼야 한다.
CREATE TABLE catalog_change_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposer_id  BIGINT NOT NULL,          -- 제안한 운영자 app_user.id (FK 아님 — 탈퇴해도 보존)
    action       TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    dataset      TEXT NOT NULL CHECK (btrim(dataset) <> '' AND length(dataset) <= 64),
    row_key      TEXT CHECK (length(row_key) <= 500),      -- CREATE 는 승인 시점에 정해지므로 NULL 가능
    payload      TEXT CHECK (length(payload) <= 8000),     -- 변경할 필드(JSON). DELETE 는 NULL
    reason       TEXT CHECK (length(reason) <= 1000),      -- 제안 사유(선택)
    status       TEXT NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'FAILED')),
    decided_by   BIGINT,                   -- 승인·거절한 운영자. PENDING 이면 NULL
    decided_at   TIMESTAMPTZ,
    decision_note TEXT CHECK (length(decision_note) <= 1000),  -- 거절 사유·반영 실패 사유
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 결정된 요청은 결정자·시각이 반드시 있고, PENDING 은 반드시 없다.
    CHECK ((status = 'PENDING') = (decided_by IS NULL AND decided_at IS NULL))
);

CREATE INDEX idx_catalog_change_request_status ON catalog_change_request(status, created_at DESC);
