-- 스마트초이스 시세 스냅샷 복구(V19). V7 이 만든 것을 V9(D-18 연동 제거)가 DROP 했고,
-- D-20/D-23 이 "검증 오버레이"로 복구하기로 하면서 다시 필요해졌다.
-- 카탈로그(시드)를 대체하지 않는다 — 교차검증·시세 참고용이다(D-12 (3)).
-- 채우는 쪽은 SmartChoiceSweepService(하루 3회 배치), 읽는 쪽은 SmartChoiceSnapshotReader 뿐이다.
-- 사용자 요청 경로는 이 표만 읽고 외부를 호출하지 않는다(D-05 유지).
CREATE TABLE smartchoice_plan_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier          TEXT NOT NULL,
    plan_name        TEXT NOT NULL,
    network_type     TEXT NOT NULL,                 -- 3G|LTE|5G (type 파라미터에서 파생)
    contract_months  INTEGER NOT NULL CHECK (contract_months >= 0),  -- dis 0|12|24
    plan_price       BIGINT NOT NULL CHECK (plan_price >= 0),
    discounted_price BIGINT NOT NULL CHECK (discounted_price >= 0),
    display_data     TEXT,
    source           TEXT NOT NULL DEFAULT '스마트초이스(KTOA)',
    source_url       TEXT NOT NULL,
    collected_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (carrier, plan_name, network_type, contract_months)   -- 격자 dedup 키(upsert)
);
-- 대조는 (통신사, 요금제명)으로 찾는다 — 리더의 조회 조건과 같은 순서로 둔다.
CREATE INDEX idx_smartchoice_snapshot_lookup ON smartchoice_plan_snapshot(carrier, plan_name);
