CREATE TABLE carrier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    carrier_type TEXT NOT NULL
);

CREATE TABLE mobile_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id BIGINT NOT NULL REFERENCES carrier(id),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    network_type TEXT NOT NULL CHECK (network_type IN ('FIVE_G', 'LTE', 'THREE_G')),
    base_price BIGINT NOT NULL CHECK (base_price > 0),
    data_mb BIGINT NOT NULL CHECK (data_mb >= 0),
    voice_min BIGINT NOT NULL CHECK (voice_min >= 0),
    sms_cnt BIGINT NOT NULL CHECK (sms_cnt >= 0),
    contract_discount_12m BIGINT CHECK (contract_discount_12m >= 0),
    contract_discount_24m BIGINT CHECK (contract_discount_24m >= 0),
    age_limit TEXT,
    source_url TEXT NOT NULL CHECK (btrim(source_url) <> ''),
    collected_at DATE NOT NULL,
    UNIQUE (carrier_id, name)
);

CREATE TABLE subscription_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    category TEXT NOT NULL,
    official_url TEXT NOT NULL CHECK (btrim(official_url) <> '')
);

CREATE TABLE subscription_tier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES subscription_service(id),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    price BIGINT NOT NULL CHECK (price >= 0),
    concurrent_streams INTEGER CHECK (concurrent_streams > 0),
    quality TEXT,
    note TEXT,
    UNIQUE (service_id, name),
    UNIQUE (id, service_id)
);

CREATE TABLE bundle_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    price BIGINT NOT NULL CHECK (price >= 0),
    provider TEXT NOT NULL
);

CREATE TABLE bundle_item (
    bundle_id BIGINT NOT NULL REFERENCES bundle_product(id),
    tier_id BIGINT NOT NULL REFERENCES subscription_tier(id),
    PRIMARY KEY (bundle_id, tier_id)
);

CREATE TABLE plan_benefit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_plan_id BIGINT NOT NULL REFERENCES mobile_plan(id),
    service_id BIGINT NOT NULL REFERENCES subscription_service(id),
    tier_id BIGINT,
    benefit_type TEXT NOT NULL CHECK (
        benefit_type IN ('FREE', 'FIXED_DISCOUNT', 'RATE_DISCOUNT', 'BUNDLE_INCLUDED')
    ),
    discount_value NUMERIC(10,2),
    is_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
    exclusive_group TEXT,
    valid_from DATE,
    valid_to DATE,
    source_url TEXT NOT NULL CHECK (btrim(source_url) <> ''),
    collected_at DATE NOT NULL,
    FOREIGN KEY (tier_id, service_id) REFERENCES subscription_tier(id, service_id),
    CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CHECK (NOT is_exclusive OR (exclusive_group IS NOT NULL AND btrim(exclusive_group) <> '')),
    CHECK (
        (benefit_type IN ('FREE', 'BUNDLE_INCLUDED') AND discount_value IS NULL)
        OR (benefit_type = 'FIXED_DISCOUNT' AND discount_value IS NOT NULL
            AND discount_value >= 0 AND discount_value = trunc(discount_value))
        OR (benefit_type = 'RATE_DISCOUNT' AND discount_value IS NOT NULL
            AND discount_value BETWEEN 0 AND 1)
    )
);

CREATE INDEX idx_plan_benefit_plan ON plan_benefit(mobile_plan_id);

CREATE TABLE merchant_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES subscription_service(id),
    pattern TEXT NOT NULL CHECK (btrim(pattern) <> ''),
    match_type TEXT NOT NULL CHECK (match_type IN ('CONTAINS', 'PREFIX')),
    UNIQUE (pattern, match_type)
);
