-- 백오피스 고도화(2026-09-18, D-52). 운영 상태·데이터 품질·퍼널 정정·결손 처리·제보 메모·추천 통계·감사 통합.

-- 3. 퍼널을 행위자 단위로 한 번만 센다. funnel_daily(원시 횟수)는 그대로 두고, 여기가 "사람 수"다.
--    actor_key: 회원은 u:<id>, 비회원은 ip:<발신지>. 결과 화면 무한 호출(9/17~18) 같은 사고가 다시 나도 이 표는 안 부푼다.
CREATE TABLE funnel_event (
    day       DATE NOT NULL,
    kind      TEXT NOT NULL,
    actor_key TEXT NOT NULL CHECK (length(actor_key) <= 80),
    PRIMARY KEY (day, kind, actor_key)
);

-- 4. 결손 처리 흐름: 진행 중 상태와 처리 메모.
ALTER TABLE catalog_candidate DROP CONSTRAINT IF EXISTS catalog_candidate_status_check;
ALTER TABLE catalog_candidate ADD CONSTRAINT catalog_candidate_status_check
    CHECK (status IN ('REQUESTED', 'IN_PROGRESS', 'PENDING', 'VERIFIED', 'REJECTED'));
ALTER TABLE catalog_candidate ADD COLUMN note VARCHAR(1000), ADD COLUMN updated_at TIMESTAMPTZ;

-- 5. 제보 처리 메모.
ALTER TABLE catalog_report ADD COLUMN note VARCHAR(1000), ADD COLUMN updated_at TIMESTAMPTZ;
ALTER TABLE service_report ADD COLUMN note VARCHAR(1000), ADD COLUMN updated_at TIMESTAMPTZ;

-- 7. 추천 통계: 날짜·1순위 요금제·데이터 구간별 횟수. 개인을 남기지 않는다.
CREATE TABLE recommendation_daily (
    day     DATE NOT NULL,
    plan_id BIGINT NOT NULL,
    data_gb INT NOT NULL,
    count   INT NOT NULL DEFAULT 1,
    PRIMARY KEY (day, plan_id, data_gb)
);

-- 8. 운영 행위 기록. catalog_audit(카탈로그 변경)과 합쳐 한 타임라인으로 본다.
CREATE TABLE admin_action (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT NOT NULL,                 -- FK 아님: 탈퇴해도 기록은 남는다(catalog_audit 과 같은 이유)
    action     TEXT NOT NULL CHECK (length(action) <= 64),
    target     TEXT CHECK (length(target) <= 200),
    detail     TEXT CHECK (length(detail) <= 1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_action_time ON admin_action(created_at DESC);
