-- Phase 1: 인증·내 구독·결제내역·탐지 결과.
-- 'user' 는 PostgreSQL 예약어라 app_user 로 둔다(docs/architecture.md §4 의 user 테이블).

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE CHECK (btrim(email) <> ''),
    password_hash TEXT NOT NULL,
    current_plan_id BIGINT REFERENCES mobile_plan(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    tier_id BIGINT NOT NULL REFERENCES subscription_tier(id),
    monthly_price BIGINT NOT NULL CHECK (monthly_price >= 0),
    started_at DATE,
    ended_at DATE,
    last_used_at DATE,
    CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);
CREATE INDEX idx_user_subscription_user ON user_subscription(user_id);

CREATE TABLE payment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    merchant_raw TEXT NOT NULL,
    service_id BIGINT REFERENCES subscription_service(id),
    amount BIGINT NOT NULL CHECK (amount >= 0),
    paid_at DATE NOT NULL,
    source TEXT NOT NULL
);
CREATE INDEX idx_payment_record_user ON payment_record(user_id);

CREATE TABLE detection_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    rule_code TEXT NOT NULL CHECK (rule_code IN ('BENEFIT_OVERLAP', 'TIER_DUPLICATE', 'BUNDLE_OVERLAP')),
    target_ref TEXT NOT NULL,
    wasted_amount BIGINT NOT NULL CHECK (wasted_amount >= 0),
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_detection_result_user ON detection_result(user_id);
