-- 개인정보 정책: 삭제권(파기) + 수집·이용 동의 기록.
-- 삭제권(파기 의무): DELETE app_user 시 개인 데이터가 전부 함께 파기되도록
-- V2 개인 테이블 FK에 ON DELETE CASCADE 를 부여한다(auth_session/auth_email_token 은 V3/V4 에서 이미 cascade).
ALTER TABLE user_subscription DROP CONSTRAINT user_subscription_user_id_fkey,
    ADD CONSTRAINT user_subscription_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
ALTER TABLE payment_record DROP CONSTRAINT payment_record_user_id_fkey,
    ADD CONSTRAINT payment_record_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
ALTER TABLE detection_result DROP CONSTRAINT detection_result_user_id_fkey,
    ADD CONSTRAINT detection_result_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;

-- 수집·이용 동의: 항목별 동의 버전·시각·철회 증빙. 필수(계약 이행)와 선택(마케팅)을 구분한다.
CREATE TABLE user_consent (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    item           VARCHAR(20) NOT NULL CHECK (item IN ('ESSENTIAL', 'MARKETING')),
    policy_version TEXT NOT NULL,
    agreed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    withdrawn_at   TIMESTAMPTZ,
    UNIQUE (user_id, item)
);
CREATE INDEX idx_user_consent_user ON user_consent(user_id);
