-- D2: 스마트초이스 Open API 격자 스윕으로 모은 요금제 라이브 시세 스냅샷.
-- 카탈로그(시드)를 대체하지 않는다 — 교차검증·시세 참고용(요금제 ID·OTT 제휴·정확 스펙 없음). data.md §2, 결정 D-10.
CREATE TABLE smartchoice_plan_snapshot (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier          TEXT NOT NULL,
    plan_name        TEXT NOT NULL,
    network_type     TEXT NOT NULL,                 -- 3G|LTE|5G (type 파라미터에서 파생)
    contract_months  INTEGER NOT NULL CHECK (contract_months >= 0),  -- dis 0|12|24
    plan_price       BIGINT NOT NULL CHECK (plan_price >= 0),
    discounted_price BIGINT NOT NULL CHECK (discounted_price >= 0),
    display_data     TEXT,
    source           TEXT NOT NULL DEFAULT '스마트초이스(KTOA)',
    source_url       TEXT NOT NULL,
    collected_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (carrier, plan_name, network_type, contract_months)   -- 격자 dedup 키(upsert)
);
CREATE INDEX idx_smartchoice_snapshot_carrier ON smartchoice_plan_snapshot(carrier);
